import { z } from "zod";
const error = "Chưa đủ thông tin";

export const formSchema = z.object({
  hoten: z.string({
    error,
  }),
  ngaysinh: z.string({ error }),
  nhapngu: z.string({ error }).min(6, { error }),
  capbac: z.string({ error }),
  chucvu: z.string({ error }),
  donvi: z.string({ error }),
  vanhoa: z.string().min(2, { error }),
  vaodoan: z.string({ error }).optional(),
  vaodang: z.string({ error }).optional(),
  dantoc: z.string({ error }),
  tongiao: z.string({ error }),
  khokhan: z.string().optional(),
  doandang: z.string().optional(),
  sohieuqn: z.string({ error }).optional(),
  capbacheso: z.string({ error }).optional(),
  thanhphan: z.string({ error }),
  thuongtru: z.string({ error }),
  sothedang: z.string().optional(),
  truocnhapngu: z.string({ error }),
  truongquandoi: z.string({ error }).optional(),
  nuocngoai: z.string({ error }).optional(),
  sotruong: z.string({ error }).optional(),
  laodongchinh: z.boolean().default(false).optional(),
  nguoithandinuocngoai: z.string().optional(),
  bomebichatdocdacam: z.string().optional(),
  conguoitrongquandoi: z.string().optional(),
  phatgiamcaitao: z.string().optional(),
  tomtatcongtac: z.string().optional(),
  hotenbo: z.string().optional(),
  namsinhbo: z.string().optional(),
  sdtbo: z.string().optional(),
  nghenghiepbo: z.string().optional(),
  nammatbo: z.string().optional(),
  quequanbo: z.string().optional(),
  truquanbo: z.string().optional(),
  hotenme: z.string().optional(),
  namsinhme: z.string().optional(),
  sdtme: z.string().optional(),
  nghenghiepme: z.string().optional(),
  nammatme: z.string().optional(),
  quequanme: z.string().optional(),
  truquanme: z.string().optional(),
  con: z.string().optional(),
  anhchiem: z.string().optional(),
});

export const userProps: Record<string, string> = {
  hoten: "Họ và tên",
  ngaysinh: "Ngày sinh",
  nhapngu: "Ngày nhập ngũ",
  capbac: "Cấp bậc",
  chucvu: "Chức vụ",
  donvi: "Đơn vị",
  vanhoa: "Trình độ văn hóa",
  vaodoan: "Ngày vào Đoàn",
  vaodang: "Ngày vào Đảng",
  dantoc: "Dân tộc",
  tongiao: "Tôn giáo",
  khokhan: "Hoàn cảnh khó khăn",
  doandang: "Đoàn Đảng",
  sohieuqn: "Số hiệu quân nhân",
  capbacheso: "Cấp bậc (hệ số)",
  thanhphan: "Thành phần gia đình",
  thuongtru: "Hộ khẩu thường trú",
  sothedang: "Số thẻ Đảng",
  truocnhapngu: "Nghề nghiệp trước khi nhập ngũ",
  truongquandoi: "Trường quân đội đã học",
  nuocngoai: "Đã đi nước ngoài",
  sotruong: "Sở trường",
  laodongchinh: "Lao động chính trong gia đình",
  nguoithandinuocngoai: "Người thân đi nước ngoài",
  bomebichatdocdacam: "Bố/mẹ bị chất độc da cam",
  conguoitrongquandoi: "Có người thân trong quân đội",
  phatgiamcaitao: "Đã từng bị phạt giam/cải tạo",
  tomtatcongtac: "Tóm tắt quá trình công tác",
  hotenbo: "Họ tên bố",
  namsinhbo: "Năm sinh bố",
  sdtbo: "SĐT bố",
  nghenghiepbo: "Nghề nghiệp bố",
  nammatbo: "Năm mất bố",
  quequanbo: "Quê quán bố",
  truquanbo: "Nơi trú quán bố",
  hotenme: "Họ tên mẹ",
  namsinhme: "Năm sinh mẹ",
  sdtme: "SĐT mẹ",
  nghenghiepme: "Nghề nghiệp mẹ",
  nammatme: "Năm mất mẹ",
  quequanme: "Quê quán mẹ",
  truquanme: "Nơi trú quán mẹ",
  con: "Con cái",
  anhchiem: "Anh chị em",
};
