export const danTocVietNam = [
  ["Kinh", "kinh"],
  ["Tày", "tay"],
  ["Thái", "thai"],
  ["Mường", "muong"],
  ["Khmer", "khmer"],
  ["Hoa", "hoa"],
  ["Nùng", "nung"],
  ["H'Mông", "hmong"],
  ["Dao", "dao"],
  ["Gia Rai", "gia-rai"],
  ["Ê Đê", "e-de"],
  ["Ba Na", "ba-na"],
  ["Sán Chay", "san-chay"],
  ["Chăm", "cham"],
  ["Xê Đăng", "xe-dang"],
  ["Sán Dìu", "san-diu"],
  ["Hrê", "hre"],
  ["Ra Glai", "ra-glai"],
  ["Mnông", "mnong"],
  ["Thổ", "tho"],
  ["Stiêng", "stieng"],
  ["Khơ Mú", "kho-mu"],
  ["Bru - Vân Kiều", "bru-van-kieu"],
  ["Cơ Tu", "co-tu"],
  ["Giáy", "giay"],
  ["Tà Ôi", "ta-oi"],
  ["Mạ", "ma"],
  ["Co", "co"],
  ["Chơ Ro", "cho-ro"],
  ["Xinh Mun", "xinh-mun"],
  ["Hà Nhì", "ha-nhi"],
  ["Chu Ru", "chu-ru"],
  ["Lào", "lao"],
  ["La Chí", "la-chi"],
  ["Phù Lá", "phu-la"],
  ["La Hủ", "la-hu"],
  ["Kháng", "khang"],
  ["Lự", "lu"],
  ["Pà Thẻn", "pa-then"],
  ["Lô Lô", "lo-lo"],
  ["Chứt", "chut"],
  ["Mảng", "mang"],
  ["Cờ Lao", "co-lao"],
  ["Bố Y", "bo-y"],
  ["Công", "cong"],
  ["Ngái", "ngai"],
  ["Si La", "si-la"],
  ["Pu Péo", "pu-peo"],
  ["Brâu", "brau"],
  ["Ơ Đu", "o-du"],
  ["Rơ Măm", "ro-mam"],
];
