export const fullColumns = [
  ["hoten", "Họ và tên"],
  ["ngaysinh", "Ngày sinh"],
  ["nhapngu", "Ngày nhập ngũ"],
  ["capbac", "Cấp bậc"],
  ["chucvu", "Chức vụ"],
  ["donvi", "Đơn vị"],
  ["vanhoa", "Trình độ văn hóa"],
  ["vaodoan", "Ngày vào Đoàn"],
  ["dantoc", "Dân tộc"],
  ["tongiao", "Tôn giáo"],
  ["doandang", "Đoàn/Đảng"],
  ["thanhphan", "Thành phần"],
  ["thuongtru", "Địa chỉ thường trú"],
  ["truocnhapngu", "Nghề trước khi nhập ngũ"],
  ["nuocngoai", "Từng ở nước ngoài"],
  ["laodongchinh", "Lao động chính"],
  ["nguoithandinuocngoai", "Có người thân định cư nước ngoài"],
  ["bomebichatdocdacam", "Cha mẹ bị chất độc da cam"],
  ["conguoitrongquandoi", "Có người thân trong quân đội"],
  ["phatgiamcaitao", "Tiền án, cải tạo"],
  ["khokhan", "Hoàn cảnh khó khăn"],
  ["hotenbo", "Họ tên bố"],
  ["namsinhbo", "Năm sinh bố"],
  ["nghenghiepbo", "Nghề nghiệp bố"],
  ["nammatbo", "Năm mất bố"],
  ["quequanbo", "Quê quán bố"],
  ["truquanbo", "Trú quán bố"],
  ["hotenme", "Họ tên mẹ"],
  ["namsinhme", "Năm sinh mẹ"],
  ["sdtme", "SĐT mẹ"],
  ["nghenghiepme", "Nghề nghiệp mẹ"],
  ["quequanme", "Quê quán mẹ"],
  ["truquanme", "Trú quán mẹ"],
  ["anhchiem", "Anh/chị em"],
];

export const shortColumns = [
  ["hoten", "Họ và tên"],
  ["ngaysinh", "Ngày sinh"],
  ["nhapngu", "Ngày nhập ngũ"],
  ["capbac", "Cấp bậc"],
  ["chucvu", "Chức vụ"],
  ["donvi", "Đơn vị"],
  ["vanhoa", "Trình độ văn hóa"],
];
